In [1]:
import math


In [2]:
math.sqrt(25)


5.0

In [3]:
import math as mt
mt.sqrt(25)
mt.pi

3.141592653589793

In [4]:
mt.sqrt(25)


5.0

In [5]:
import numpy
import scipy

In [8]:
from numpy import random

In [7]:
from scipy import stats


In [9]:
import numpy as np

In [10]:
#uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [11]:
print(dataOne)

[[0.97268365 0.84911306 0.30217782 0.90426199 0.40146748]
 [0.23049777 0.70322635 0.33267666 0.11789683 0.11938408]
 [0.02075935 0.34625235 0.79082868 0.01566133 0.70883009]
 [0.36495885 0.83829869 0.55177427 0.38662788 0.14545743]
 [0.86842776 0.86714121 0.25264909 0.8334759  0.08912444]]


In [12]:
np.mean(dataOne)

0.48054612047924655

In [13]:
math.pow(10,5)

100000.0

In [14]:
stats.median_high(dataOne)

AttributeError: module 'scipy.stats' has no attribute 'median_high'

In [15]:
stats.itemfreq(dataOne)

C:\Users\josedct\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  """Entry point for launching an IPython kernel.


array([[0.01566133, 1.        ],
       [0.02075935, 1.        ],
       [0.08912444, 1.        ],
       [0.11789683, 1.        ],
       [0.11938408, 1.        ],
       [0.14545743, 1.        ],
       [0.23049777, 1.        ],
       [0.25264909, 1.        ],
       [0.30217782, 1.        ],
       [0.33267666, 1.        ],
       [0.34625235, 1.        ],
       [0.36495885, 1.        ],
       [0.38662788, 1.        ],
       [0.40146748, 1.        ],
       [0.55177427, 1.        ],
       [0.70322635, 1.        ],
       [0.70883009, 1.        ],
       [0.79082868, 1.        ],
       [0.8334759 , 1.        ],
       [0.83829869, 1.        ],
       [0.84911306, 1.        ],
       [0.86714121, 1.        ],
       [0.86842776, 1.        ],
       [0.90426199, 1.        ],
       [0.97268365, 1.        ]])

In [16]:
print('I love data Science')

I love data Science


In [19]:
variableName = 25
variableName1 = 'I love data science'
print(variableName1 + '.')

I love data science.


In [20]:
type(variableName)

int

In [21]:
doubleVar = 25.0
type(doubleVar)

float

In [22]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [25]:
varOne = 25
varTwo = ' Hello'
varThree = str(varOne) + varTwo
print(varThree)

25 Hello


In [27]:
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [29]:
tel = {'jack': 4098, 'sape': 4139}

In [30]:
tel['jack']

4098

In [31]:
numbers = {'One': 1,'Two': 2,'Three': 3,'Four': 4,'Five': 5}
print(numbers)

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}


In [32]:
print(numbers['Four'])

4


In [33]:
math.pow(numbers['Five'], numbers['Two'])

25.0